<#
.SYNOPSIS
    Standardized subagent consultation request tool.
.DESCRIPTION
    Creates a structured consultation request for Oracle, Designer, Librarian, or Explorer.
    Tracks consultation history and outcomes.
.PARAMETER Agent
    Target agent for consultation: Oracle, Designer, Librarian, Explorer.
.PARAMETER Topic
    Brief topic of the consultation.
.PARAMETER Context
    Detailed context for the consultation.
.PARAMETER DecisionId
    Related decision ID.
.PARAMETER RequestingAgent
    Agent making the request.
.PARAMETER Urgency
    Urgency level: Immediate, Normal, Low.
.EXAMPLE
    .\Request-Consultation.ps1 -Agent "Oracle" -Topic "Validate retry logic" -Context "Need risk assessment for exponential backoff implementation" -DecisionId "INFRA-037" -RequestingAgent "WindFixer"
#>
param(
    [Parameter(Mandatory)][ValidateSet("Oracle","Designer","Librarian","Explorer")][string]$Agent,
    [Parameter(Mandatory)][string]$Topic,
    [Parameter(Mandatory)][string]$Context,
    [string]$DecisionId = "",
    [string]$RequestingAgent = "Strategist",
    [ValidateSet("Immediate","Normal","Low")][string]$Urgency = "Normal"
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
$consultDir = Join-Path $repoRoot "STR4TEG15T\consultations\$($Agent.ToLower())"
if (-not (Test-Path $consultDir)) { New-Item -ItemType Directory -Path $consultDir -Force | Out-Null }

$consultId = "CONSULT-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
$consultFile = Join-Path $consultDir "$consultId.md"
$timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"

$agentScope = switch ($Agent) {
    "Oracle"    { "Validation, risk assessment, security review" }
    "Designer"  { "Architecture, file structure, design patterns" }
    "Librarian" { "Research, documentation, knowledge gaps" }
    "Explorer"  { "Discovery, pattern matching, code search" }
}

$agentPrompt = switch ($Agent) {
    "Oracle"    { "Evaluate risks, validate approach, identify security concerns." }
    "Designer"  { "Propose architecture, suggest file organization, review design." }
    "Librarian" { "Research topic, find documentation, fill knowledge gaps." }
    "Explorer"  { "Search codebase, find patterns, discover related implementations." }
}

$content = @"
# Consultation Request: $consultId

**Target Agent**: @$($Agent.ToLower())
**Requested By**: $RequestingAgent
**Decision**: $(if ($DecisionId) { $DecisionId } else { "N/A" })
**Urgency**: $Urgency
**Status**: PENDING
**Created**: $timestamp

---

## Topic

$Topic

## Context

$Context

## Agent Scope

$agentScope

## Expected Output

$agentPrompt

## Response

_Awaiting $Agent response._

## Outcome

_To be filled after consultation._

---

## Delegation Command

``````
@$($Agent.ToLower()) $Topic
Context: $Context
Decision: $(if ($DecisionId) { $DecisionId } else { "N/A" })
Requested by: $RequestingAgent
``````

---

*Generated by consultation-requester tool at $timestamp*
"@

Set-Content -Path $consultFile -Value $content -Encoding UTF8
Write-Host "Consultation request created: $consultFile" -ForegroundColor Cyan
Write-Host "Target: @$($Agent.ToLower()) | Topic: $Topic" -ForegroundColor White
Write-Host "Urgency: $Urgency" -ForegroundColor $(if ($Urgency -eq "Immediate") { "Red" } elseif ($Urgency -eq "Normal") { "Yellow" } else { "White" })

return $consultId
