<#
.SYNOPSIS
    Structured bug reporting tool for Forgewright delegation.
.DESCRIPTION
    Creates a structured bug report and optionally delegates to Forgewright.
    Used when any agent encounters a blocking bug during implementation.
.PARAMETER DecisionId
    Decision where the bug was found.
.PARAMETER Agent
    Agent that encountered the bug.
.PARAMETER ErrorMessage
    The error message or description.
.PARAMETER FilePath
    File path where the bug occurs.
.PARAMETER LineNumber
    Line number of the error (optional).
.PARAMETER Severity
    Bug severity: Critical, High, Medium, Low.
.PARAMETER StackTrace
    Optional stack trace.
.EXAMPLE
    .\Report-Bug.ps1 -DecisionId "TEST-035" -Agent "WindFixer" -ErrorMessage "NullRef in TestOrchestrator" -FilePath "UNI7T35T/TestHarness/TestOrchestrator.cs" -LineNumber 42 -Severity "High"
#>
param(
    [Parameter(Mandatory)][string]$DecisionId,
    [Parameter(Mandatory)][string]$Agent,
    [Parameter(Mandatory)][string]$ErrorMessage,
    [string]$FilePath = "",
    [int]$LineNumber = 0,
    [ValidateSet("Critical","High","Medium","Low")][string]$Severity = "Medium",
    [string]$ErrorStackTrace = ""
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
$bugsDir = Join-Path $repoRoot "STR4TEG15T\tools\bug-reporter\reports"
if (-not (Test-Path $bugsDir)) { New-Item -ItemType Directory -Path $bugsDir -Force | Out-Null }

$bugId = "BUG-$(Get-Date -Format 'yyyyMMdd-HHmmss')-$([guid]::NewGuid().ToString('N').Substring(0,6))"
$bugFile = Join-Path $bugsDir "$bugId.md"
$timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"

$location = if ($FilePath -and $LineNumber -gt 0) { "$FilePath`:$LineNumber" } elseif ($FilePath) { $FilePath } else { "Unknown" }

$report = @"
# Bug Report: $bugId

**Decision**: $DecisionId
**Reported By**: $Agent
**Severity**: $Severity
**Status**: OPEN
**Created**: $timestamp

---

## Error

``````
$ErrorMessage
``````

## Location

- **File**: $location
- **Line**: $(if ($LineNumber -gt 0) { $LineNumber } else { "N/A" })

## Stack Trace

``````
$(if ($ErrorStackTrace) { $ErrorStackTrace } else { "Not provided" })
``````

## Context

Bug encountered by $Agent during implementation of $DecisionId.

## Resolution

_To be filled by Forgewright._

---

## Forgewright Delegation

``````
@forgewright Fix bug encountered by $($Agent):
- Decision: $DecisionId
- Error: $ErrorMessage
- File: $location
- Context: Blocking progress on $DecisionId implementation
``````

---

*Generated by bug-reporter tool at $timestamp*
"@

Set-Content -Path $bugFile -Value $report -Encoding UTF8
Write-Host "Bug report created: $bugFile" -ForegroundColor Yellow
Write-Host "Bug ID: $bugId" -ForegroundColor Cyan
Write-Host "Severity: $Severity" -ForegroundColor $(if ($Severity -eq "Critical") { "Red" } elseif ($Severity -eq "High") { "Yellow" } else { "White" })

# Return the bug ID for programmatic use
return $bugId
